name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec

  release_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: apk add --update --upgrade --no-cache --force-overwrite libsqlite-dev
      - run: shards build --production --release --static --no-debug
